#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    if dpkg --compare-versions "$2" 'lt-nl' '2018.07.30~' && which gpg >/dev/null && which apt-key >/dev/null; then
        KEYRING="/etc/apt/trusted.gpg"
        eval $(apt-config shell KEYFILE Apt::GPGV::TrustedKeyring)
        eval $(apt-config shell KEYFILE Dir::Etc::Trusted/f)
        if [ -e "$KEYFILE" ]; then
            apt-key --keyring "$KEYFILE" del 4BE37A90 >/dev/null 2>&1 || :
        fi
    fi
fi

#DEBHELPER#
